- _layouts/base.html
- _sass/_settings.scss
- _sass/styles.scss
- docs/pro-tips.md
- index.html
- js/tabs.js
- package.json
- yarn.lock
- Add `Get started` button to hero
- Add tabs for Linux, Windows and macOS installation steps
- Move tips to docs
- Upgrade to vanilla 2.4.1
- Upgrade `global-nav` to 2.2.1
- download this branch
- run the site https://0.0.0.0:8039 and https://0.0.0.0:8039/docs/pro-tips
- compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1982)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1983
> Add tabs to the home page

- _layouts/base.html
- index.html
- Add copy doc to front-matter
- [Requested](https://github.com/canonical-web-and-design/ubuntu-copy-docs/issues/7) that this site is added to the google/firefox extensions
- Fixed minor text update found in the copy doc
- See that the meta name="copydoc" has a copy doc in the value
- See that the page mirrors the [copydoc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit?usp=sharing)
> Add copy doc to site and fixed up text on homepage

- index.html
Added the additional parameters to the quick-run steps to allow this to work on macOS and Windows 10 from the host side, as intended. This should help close [issue 19](https://github.com/canonical-web-and-design/microstack.run/issues/19).
> Added the additional parameters to the quick-run steps to allow this to work on macOS and Windows 10 from the host side, as intended. 

- .stylelintrc
- _sass/_blockquote.scss
- _sass/_docs.scss
- _sass/_settings.scss
- _sass/_sidebar.scss
- _sass/styles.scss
- package.json
- run
- yarn.lock
Replaces sass-lint with stylelint and fixed resulting linting errors
- Run `./run exec yarn lint-scss`
- Check that there are no linting errors
Fixes #30
> Replace sass-lint with stylelint

- renovate.json
Disable renovate to avoid upgrades to ruby 2.7.
> Disable renovate for ruby

- _layouts/docs.html
Added an `<hr>` to the docs template to give a line between the content and the footer
- View the site locally in your web browser at: http://0.0.0.0:8039/docs
- See the line above the footer like on other pages
Fixes #33
> Add HR to buttom of docs layout

- _layouts/base.html
- index.html
- Move to use fixed multipass.run download links
- See that the multipass windows and macos downloads point to multipass.run/download/windows and macos
> Move to use fixed multipass.run download links

- .env
- static/js/typer.js
- templates/index.html
- templates/partial/_navigation.html
Rebuild MicroStack home page
- Please check page against [copy doc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit) and and resolve comments
- Check against [design](https://app.zeplin.io/project/611e22af1491325814021275/screen/611e22e82bc2085acc4bc1df)
Fixes [#4351](https://github.com/canonical-web-and-design/web-squad/issues/4351)
> Rebuild MicroStack home page

- static/sass/_row-cli.scss
- static/sass/styles.scss
- templates/index.html
- Replaced the `<pre>` and `<code>` element with `<div>` with styles
- Added `_row-cli.scss` file in static/sass for styles
- Please check if the code snippet's animation is working well and it's responsive according to screen size
Fixes #127
> Remove horizontal scroll bar

- Dockerfile
Node 16 is latest LTS, we should be using it everywhere.
It works, I checked it! But you can too!
``` bash
docker build -t microstacknode16 .
docker run --env SECRET_KEY=dfgsdf -ti -p 8080:80 microstacknode16
```
Go to http://localhost:8080. Check the site works.
> Update to node 16 for production docker images

- templates/base_layout.html
- templates/index.html
- templates/partial/_footer.html
- Updated the homepage with changes requested in the [copy doc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit)
- Fixed the copydoc metatag
- See that the page matches the copy doc (note: the comments around images and quotes aren't addressed in this PR, I've asked Tytus if they're still valid and am waiting on a response)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4740
> Homepage copy updates

- templates/base_layout.html
- Updated the meta description according to the [copy doc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit)
- Inspect the page source and see that the meta tags for `description`, `twitter:description` and `og:description` have been updated and match the copy doc
Fixes [#4758](https://github.com/canonical-web-and-design/web-squad/issues/4758)
> Update index meta description copy

- templates/index.html
Updated index as per [copy doc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit#)
- Demo: https://microstack-run-162.demos.haus
- Check against copy doc and make sure all comments have been addressed 
- Check that links work as expected 
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4754
> Added openstack tutorials link

- templates/index.html
- Updated page as per [copy doc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit#heading=h.dsxw6o6hnq74)
- See that the requested changes have been made (have to click through each OS option)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5025
> Update installation instructions to remove `devmode`

- redirects.yaml
Added a redirect from /survey to a Usabilla URL, the idea being that Tytus and co can use microstack.run/survey in CLI output to drive engagement with a survey they're running.
- visit https://microstack-run-199.demos.haus/survey
- see that you are redirected to a Usabilla survey
Fixes https://github.com/canonical/web-squad/issues/6095
> add a redirect for /survey to a usabilla survey

- requirements.txt
Microstack.run is using the bad version of canonicalwebteam.discourse which leads to index page caching.
Fixes https://warthogs.atlassian.net/browse/WD-4503
Fixes https://github.com/canonical/canonicalwebteam.discourse/issues/165
Go to https://microstack-run-233.demos.haus/docs. Change some content. Refresh.
Bear in mind that page rules set cache timeout to 1 minute anyway, so it might take 1 minute for your browser to show you the latest version.
> Use latest discourse module to fix caching issue

- templates/docs/document.html
Replace microk8s with microstack in title for docs pages
- View the site locally in your web browser at: http://0.0.0.0:8039/docs
- Check tab title now says MicroStack - .. instead of MicroK8s - ...
> Replace microk8s with microstack in title for docs pages

- static/sass/_settings.scss
- templates/index.html
- Embbed 'how to install openstack' video in homepage based on [copydoc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit)
- [List additional steps to QA the new features or prove the bug has been resolved]
Fixes https://warthogs.atlassian.net/browse/WD-6019
> Embbed 'how to install openstack' video in homepage

- templates/partial/_navigation.html
- Changed Forum to Chat in the nav bar
- [copy doc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit#heading=h.4t7jro4ogj)
- [demo link](https://microstack-run-246.demos.haus/)
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Be sure to test on mobile, tablet and desktop screen sizes
-  Check that nav text is correct
[WD-7449](https://warthogs.atlassian.net/browse/WD-7449)
Fixes #
[WD-7449]: https://warthogs.atlassian.net/browse/WD-7449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-7449 - update forum to chat on nav

- templates/partial/_navigation.html
- Updated link to Chat in the nav bar
- [copy doc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit#heading=h.4t7jro4ogj)
- [demo link](https://microstack-run-247.demos.haus/)
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Be sure to test on mobile, tablet and desktop screen sizes
-  Check that link to Chat is correct
[WD-7449](https://warthogs.atlassian.net/browse/WD-7449)
Fixes #
[WD-7449]: https://warthogs.atlassian.net/browse/WD-7449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-7449 - update link to Chat

- templates/partial/_navigation.html
- Updated link to Chat in the nav bar
- [copy doc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit)
- [demo link](https://microstack-run-250.demos.haus/)
- Run the site using the command `./run serve` or `dotrun`
- Be sure to test on mobile, tablet and desktop screen sizes
-  Check that link to Chat is correct
[WD-8501](https://warthogs.atlassian.net/browse/WD-8501)
Fixes #
[WD-8501]: https://warthogs.atlassian.net/browse/WD-8501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-8501 - update chat nav link

- .github/workflows/pr.yaml
- Switched to dotrun for tests
- Check that the CI job `test-python` completes successfully
Fixes [Failing CI action](https://github.com/canonical/microstack.run/actions/runs/8925291718/job/24513634166?pr=255)
> Use dotrun for tests

- templates/index.html
Fix sunbeam launch typo
- [List additional steps to QA the new features or prove the bug has been resolved]
Fixes LP #2066257
> Fix sunbeam launch typo

- templates/index.html
Copyupdate: Added a flag to "install openstack instruction"
- [Copydoc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit)
Fixes # [WD-11587](https://warthogs.atlassian.net/browse/WD-11587)
[WD-11587]: https://warthogs.atlassian.net/browse/WD-11587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-11587 Copyupdate: Added a flag to "install openstack instruction"
