canonical/microstack.run

_layouts/base.html, index.html
=> Fix wrong links

index.html, js/installversion.js, js/osselector.js
- Update the text of the homepage
- Update the install instructions
- download this branch
- run the site
- compare to the [copy doc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit#)
- See the mac/windows instructions are updated
=> Update page for edge launch

_layouts/base.html, index.html
- Defer `installversion`, `osselector` & `copytoclipboard` scripts and move them to `head`
##QA
- Go to http://0.0.0.0:8039/ and check if it works as expected
Fixes #11
=> Defer scripts and move them to head

_layouts/base.html
- check the demo on a phone
- see that the site is responsive
=> Add device width scaling

_layouts/base.html
- Add jekyll variable for the copyright date
- Download the repo
- ./run the site
- See that the copyright date is correct
Fixes #16
=> Add jekyll variable for the copyright date

.circleci/config.yml, .dockerignore, Dockerfile, nginx.conf
- `export DOCKER_BUILDKIT=1`
- Build image with new dockerfile `docker build --tag myimage --build-arg BUILD_ID=myfakeid .`
- Run conainter with this image `docker run -ti -p 8111:80 myimage`
- Check build_id is present `curl localhost:8111`
Fixes #20
=> Multi-stage builds

docs/index.md
Also refactor a little.
Don't merge until [software](https://review.opendev.org/#/c/706168/) has been landed.
I've asked Pete Vander Giessen to review.
=> Add edge to achieve confinement

index.html
I've asked Pete Vander Giessen to review.
=> Move standard install from edge to beta

index.html
Added preview state notification 
- See the notification under the hero
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7346
=> Add preview notice

docs/index.md
This is related to [this bug](https://bugs.launchpad.net/microstack/+bug/1880974/).
=> Add a note about a physical platform being necessary

.gitignore, package.json, static/js/cookie-policy.js, static/sass/styles.scss, templates/partial/_footer.html, webpack.config.js, yarn.lock
- Add the new cookie module to the site
- See the new cookie popup and try the settings
- Test the "Manage your tracker settings" link from the footer
Fixes #67
=> Add cookie policy

templates/index.html
Update instructions on microstack.run index
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit#heading=h.hwnbhxv9c501)
=> Update instructions on microstack.run index

package.json, yarn.lock
- Switch to sass from node-sass
- Check the Jenkins job doesn't fail
=> Switch to sass from node-sass

.github/workflows/docs-links.yaml
=> Docs linkchecker

.github/workflows/docs-links.yaml
Update docs schedule to weekly
- Check code
=> Update docs schedule to weekly

requirements.txt, templates/docs/document.html, webapp/app.py
Update discourse module for microstack.
This task is part of [openstack/install refresh](https://github.com/canonical-web-and-design/web-squad/issues/4268)
- Check https://microstack-run-116.demos.haus/docs against temporary [index topic](https://discourse.ubuntu.com/t/about-microstack-documentation/23346)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4270
=> Update discourse module to v4

.github/workflows/docs-links.yaml, .github/workflows/pr.yaml, static/sass/_blockquote.scss
- Adds inclusive naming github action
- Replaces key non-inclusive language
- Rename 'master' to 'main'
- Check github action works
- Check language changes make lexical sense
- Fixes: https://github.com/canonical-web-and-design/web-squad/issues/4489
=> Add inclusive naming action

templates/base_layout.html
- Updated title meta tag, according to the most recent comment in the [copy doc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit?disco=AAAASkx6hEs)
- Compare the copy in the code to the copy doc
=> Update title meta tag

templates/partial/_navigation.html
Update nav for menu on mobile screen
- Please QA on mobile, tablet and desktop screen sizes
Fixes #182
=> Update nav for menu on mobile screen

requirements.txt, templates/base_layout.html, templates/index.html, webapp/app.py
- Added survey section according to [copy doc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit#)
- Also added the image template module
- View the site locally in your web browser at: https://microstack-run-189.demos.haus/
- See that the new survey section matches the copy doc
Fixes https://app.zenhub.com/workspace/o/canonical-web-and-design/web-squad/issues/5572
[if relevant, include a screenshot]
=> Add OpenStack survey

package.json, static/js/global-nav.js, static/sass/styles.scss, templates/base_layout.html, templates/partial/_navigation.html, yarn.lock
Added new nav branding and global nav
- Visit https://microstack-run-202.demos.haus/
- See that the navigation has been updated with the new branding, and works across desktop and mobile
Fixes https://github.com/canonical/web-squad/issues/5642
=> update navigation with new branding and global nav

static/js/tabs.js, templates/base_layout.html, templates/index.html, templates/partial/_navigation.html
**BLOCKED** by [this brand issue](https://warthogs.atlassian.net/browse/WD-1195)
- Refreshes homepage based on changes in the [copydoc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit#)
- An issue has been created to address Lyubo's comments on inconsistant stroke thickness that can be tracked [here](https://warthogs.atlassian.net/browse/WD-1195)
- Go to https://microstack-run-214.demos.haus/ and compare against [copydoc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit#)
- Check that all six individual tabs work and don't interfere with each other
Fixes https://github.com/canonical/web-squad/issues/6311
=> Refresh homepage

templates/docs/document.html
Look at the documents, see if they have titles.
=> The poor documents need titles

templates/index.html
- Added datasheet CTA as per [doc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit)
- View the site locally in your web browser at: https://microstack-run-236.demos.haus/
- See that the CTA is there and works as expected
Fixes https://warthogs.atlassian.net/browse/WD-4569
=> Add datasheet CTA

templates/index.html
Update the report a bug launchpad URL
- Check out the [demo here](https://microstack-run-240.demos.haus/) and compare it with the changes requested in the [copy doc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit).
- [WD-5129](https://warthogs.atlassian.net/browse/WD-5129)
[WD-5129]: https://warthogs.atlassian.net/browse/WD-5129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [copy update] WD-5129 update report a bug links

templates/index.html
- Updated copy as per [doc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit)
- View the site locally in your web browser at: https://microstack-run-241.demos.haus/
- See that the requested change was made
Fixes https://warthogs.atlassian.net/browse/WD-5677
=> Update copy on landing page

.github/workflows/pr.yaml, templates/index.html
- Removed obsolete tabs and updated copy as per [doc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit)
- View the site locally in your web browser at: https://microstack-run-255.demos.haus/
- See that the requested changes have been made
Fixes https://warthogs.atlassian.net/browse/WD-10909
=> Remove tabs and apply copy updates

templates/partial/_navigation.html
- Go to https://microstack-run-263.demos.haus/ and click on "Contribute" in the navigation, it should work now
Fixes https://github.com/canonical/microstack.run/issues/253
Fixes https://github.com/canonical/microstack.run/issues/251
=> Fix contribute link

templates/index.html
Minor copy change requested in https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit
- Visit the index page
- See that the change is live
Fixes #
[if relevant, include a screenshot]
=> copy update 
